name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: EC2 접속 및 도커 재실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/capstone/llm-collaboration-helper
            git fetch origin main
            git reset --hard origin/main

            cd ..
            docker compose up -d --build backend
            docker compose up -d --build frontend
            docker compose up -d --build python
            docker image prune -f
